#!/usr/bin/env python3
"""Merge protein and ligand GRO coordinate files with atom-count validation."""

from __future__ import annotations

import argparse
from pathlib import Path


def read_gro(path: Path) -> tuple[str, int, list[str], str]:
    lines = path.read_text(encoding="utf-8", errors="strict").splitlines()

    if len(lines) < 3:
        raise ValueError(f"{path} is too short to be a valid GRO file.")

    title = lines[0]
    try:
        atom_count = int(lines[1].strip())
    except ValueError as exc:
        raise ValueError(f"Invalid atom-count line in {path}: {lines[1]!r}") from exc

    coordinate_lines = lines[2:-1]
    box_line = lines[-1]

    if len(coordinate_lines) != atom_count:
        raise ValueError(
            f"{path}: header declares {atom_count} atoms, "
            f"but {len(coordinate_lines)} coordinate lines were found."
        )

    return title, atom_count, coordinate_lines, box_line


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--protein", required=True, type=Path)
    parser.add_argument("--ligand", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    _, protein_count, protein_atoms, protein_box = read_gro(args.protein)
    _, ligand_count, ligand_atoms, _ = read_gro(args.ligand)

    total = protein_count + ligand_count
    output_lines = [
        "Protein-ligand complex generated by merge_gro.py",
        f"{total:5d}",
        *protein_atoms,
        *ligand_atoms,
        protein_box,
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output_lines) + "\n", encoding="utf-8")

    print("Protein atoms:", protein_count)
    print("Ligand atoms:", ligand_count)
    print("Total atoms:", total)
    print("Output:", args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
